package com.example.protection.utils

import android.content.ContentValues
import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.widget.Toast
import java.io.IOException

object KycPdfGenerator {

    fun generateKycPdf(
        context: Context,
        name: String,
        email: String,
        id: String,
        age: String,
        phone: String,
        emergency: String,
        address: String,
        passportNum: String,
        aadharNum: String,
        panNum: String
    ) {
        val pageWidth = 595
        val pageHeight = 842
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        // --- Paints ---
        val titlePaint = Paint().apply {
            color = Color.BLACK
            textSize = 24f
            isFakeBoldText = true
            textAlign = Paint.Align.CENTER
        }
        val headerPaint = Paint().apply {
            color = Color.rgb(0, 102, 204) // Professional Blue
            textSize = 14f
            isFakeBoldText = true
        }
        val textPaint = Paint().apply {
            color = Color.BLACK
            textSize = 12f
        }
        val labelPaint = Paint().apply {
            color = Color.DKGRAY
            textSize = 12f
            isFakeBoldText = true
        }
        val linePaint = Paint().apply {
            color = Color.LTGRAY
            strokeWidth = 1f
        }

        // --- Header ---
        canvas.drawText("NEUTRON EMPLOYEE BIO-DATA", pageWidth / 2f, 50f, titlePaint)
        canvas.drawLine(40f, 70f, pageWidth - 40f, 70f, linePaint)

        var yPos = 110f
        val xPos = 50f
        val valueXPos = 200f // Align values in a column

        // --- Helper to draw aligned row ---
        fun drawRow(label: String, value: String) {
            canvas.drawText(label, xPos, yPos, labelPaint)
            canvas.drawText(if(value.isEmpty()) "N/A" else value, valueXPos, yPos, textPaint)
            yPos += 25f
        }

        // --- Section 1: Personal Info ---
        canvas.drawText("PERSONAL DETAILS", xPos, yPos, headerPaint)
        yPos += 30f

        drawRow("Full Name:", name)
        drawRow("Employee ID:", id)
        drawRow("Email Address:", email)
        drawRow("Age:", age)
        drawRow("Contact Number:", phone)
        drawRow("Emergency Contact:", emergency)

        // Address Handling
        canvas.drawText("Permanent Address:", xPos, yPos, labelPaint)
        val addressLines = splitText(address, 50)
        addressLines.forEach {
            canvas.drawText(it, valueXPos, yPos, textPaint)
            yPos += 15f
        }
        yPos += 20f

        canvas.drawLine(40f, yPos, pageWidth - 40f, yPos, linePaint)
        yPos += 40f

        // --- Section 2: Identity Proofs ---
        canvas.drawText("IDENTITY DOCUMENTS", xPos, yPos, headerPaint)
        yPos += 30f

        drawRow("Aadhar Number:", aadharNum)
        drawRow("PAN Number:", panNum)
        drawRow("Passport Number:", passportNum)

        // --- Footer ---
        yPos = pageHeight - 60f
        canvas.drawLine(40f, yPos, pageWidth - 40f, yPos, linePaint)
        canvas.drawText("Generated by Neutron App • Confidential Document", pageWidth / 2f, yPos + 20f,
            Paint().apply { color = Color.GRAY; textSize = 10f; textAlign = Paint.Align.CENTER })

        pdfDocument.finishPage(page)
        savePdfToStorage(context, pdfDocument, "KYC_${name}_$id.pdf")
    }

    private fun splitText(text: String, maxLength: Int): List<String> {
        val words = text.split(" ")
        val lines = mutableListOf<String>()
        var currentLine = StringBuilder()
        for (word in words) {
            if (currentLine.length + word.length + 1 > maxLength) {
                lines.add(currentLine.toString())
                currentLine = StringBuilder()
            }
            if (currentLine.isNotEmpty()) currentLine.append(" ")
            currentLine.append(word)
        }
        if (currentLine.isNotEmpty()) lines.add(currentLine.toString())
        return lines
    }

    private fun savePdfToStorage(context: Context, pdfDocument: PdfDocument, fileName: String) {
        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                val contentValues = ContentValues().apply {
                    put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                    put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                    put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS + "/NeutronKYC")
                }
                val uri = context.contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI, contentValues)
                uri?.let {
                    context.contentResolver.openOutputStream(it)?.use { outputStream ->
                        pdfDocument.writeTo(outputStream)
                    }
                    Toast.makeText(context, "Bio-Data Saved to Downloads!", Toast.LENGTH_LONG).show()
                }
            } else {
                Toast.makeText(context, "Version not supported", Toast.LENGTH_SHORT).show()
            }
        } catch (e: IOException) {
            e.printStackTrace()
        } finally {
            pdfDocument.close()
        }
    }
}